apiVersion: 1

datasources:
  - name: Elasticsearch Logs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "fastapi-logs*"
    isDefault: true
    jsonData:
      esVersion: 8
      timeField: "@timestamp"
      logMessageField: "message"
      logLevelField: "level"
      interval: "10s"
      maxConcurrentShardRequests: 256

